
/**
 * Do not edit directly, this file was auto-generated.
 */



package se.seb.gds.tokens

import androidx.compose.ui.graphics.Color

data class GdsColorTokens (
  val l101: Color,
  val l102: Color,
  val l1Brand01: Color,
  val l1Inversed: Color,
  val l201: Color,
  val l202: Color,
  val l203: Color,
  val l2Brand01: Color,
  val l2Brand02: Color,
  val l2Positive01: Color,
  val l2Negative01: Color,
  val l2Warning01: Color,
  val l2Information01: Color,
  val l2Notice01: Color,
  val l3Brand01: Color,
  val l3Brand02: Color,
  val l3Brand03: Color,
  val l301: Color,
  val l302: Color,
  val l303: Color,
  val l304: Color,
  val l3Positive01: Color,
  val l3Positive02: Color,
  val l3Positive03: Color,
  val l3Negative01: Color,
  val l3Negative02: Color,
  val l3Negative03: Color,
  val l3Notice01: Color,
  val l3Notice02: Color,
  val l3Notice03: Color,
  val l3Warning01: Color,
  val l3Warning02: Color,
  val l3Warning03: Color,
  val l3Information01: Color,
  val l3Information02: Color,
  val l3Information03: Color,
  val l3Disabled01: Color,
  val l3Disabled02: Color,
  val l3Disabled03: Color,
  val borderInteractive: Color,
  val borderSubtle01: Color,
  val borderSubtle02: Color,
  val borderStrong: Color,
  val borderInverse: Color,
  val borderInformation: Color,
  val borderPositive: Color,
  val borderNegative: Color,
  val borderWarning: Color,
  val borderNotice: Color,
  val contentContent01: Color,
  val contentContent02: Color,
  val contentContent03: Color,
  val contentContentInversed: Color,
  val contentContentBrand01: Color,
  val contentContentBrand02: Color,
  val contentContentPositive01: Color,
  val contentContentPositive02: Color,
  val contentContentNegative01: Color,
  val contentContentNegative02: Color,
  val contentContentWarning01: Color,
  val contentContentWarning02: Color,
  val contentContentNotice01: Color,
  val contentContentNotice02: Color,
  val contentContentDisabled01: Color,
  val contentContentDisabled02: Color,
  val stateDarkHover: Color,
  val stateDarkPressed: Color,
  val stateLightHover: Color,
  val stateLightPressed: Color,
  val statePositiveHover: Color,
  val statePositivePressed: Color,
  val stateNegativeHover: Color,
  val stateNegativePressed: Color,
  val stateNoticeHover: Color,
  val stateNoticePressed: Color,
  val stateWarningHover: Color,
  val stateWarningPressed: Color,
)
