
/**
 * Do not edit directly, this file was auto-generated.
 */



package se.seb.gds.tokens

import androidx.compose.ui.graphics.Color

data class GdsColorTokens (
  val L1Neutral01: Color,
  val L1Neutral02: Color,
  val L1Brand01: Color,
  val L1Inversed: Color,
  val L2Neutral01: Color,
  val L2Neutral02: Color,
  val L2Neutral03: Color,
  val L2Brand01: Color,
  val L2Brand02: Color,
  val L2Positive01: Color,
  val L2Negative01: Color,
  val L2Warning01: Color,
  val L2Information01: Color,
  val L2Notice01: Color,
  val L3Brand01: Color,
  val L3Brand02: Color,
  val L3Brand03: Color,
  val L3Neutral01: Color,
  val L3Neutral02: Color,
  val L3Neutral03: Color,
  val L3Neutral04: Color,
  val L3Neutral05: Color,
  val L3Positive01: Color,
  val L3Positive02: Color,
  val L3Positive03: Color,
  val L3Negative01: Color,
  val L3Negative02: Color,
  val L3Negative03: Color,
  val L3Notice01: Color,
  val L3Notice02: Color,
  val L3Notice03: Color,
  val L3Warning01: Color,
  val L3Warning02: Color,
  val L3Warning03: Color,
  val L3Information01: Color,
  val L3Information02: Color,
  val L3Information03: Color,
  val L3Disabled01: Color,
  val L3Disabled02: Color,
  val L3Disabled03: Color,
  val BorderInteractive: Color,
  val BorderSubtle01: Color,
  val BorderSubtle02: Color,
  val BorderStrong: Color,
  val BorderInverse: Color,
  val BorderInformation01: Color,
  val BorderPositive01: Color,
  val BorderNegative01: Color,
  val BorderWarning01: Color,
  val BorderNotice01: Color,
  val BorderInformation02: Color,
  val BorderPositive02: Color,
  val BorderNegative02: Color,
  val BorderWarning02: Color,
  val BorderNotice02: Color,
  val ContentNeutral01: Color,
  val ContentNeutral02: Color,
  val ContentNeutral03: Color,
  val ContentNeutral04: Color,
  val ContentInversed: Color,
  val ContentBrand01: Color,
  val ContentBrand02: Color,
  val ContentPositive01: Color,
  val ContentPositive02: Color,
  val ContentPositive03: Color,
  val ContentNegative01: Color,
  val ContentNegative02: Color,
  val ContentWarning01: Color,
  val ContentWarning02: Color,
  val ContentNotice01: Color,
  val ContentNotice02: Color,
  val ContentDisabled01: Color,
  val ContentDisabled02: Color,
  val StateBrand01: Color,
  val StateBrand02: Color,
  val StateBrand03: Color,
  val StateBrand04: Color,
  val StateBrand05: Color,
  val StateBrand06: Color,
  val StateNeutral01: Color,
  val StateNeutral02: Color,
  val StateNeutral03: Color,
  val StateNeutral04: Color,
  val StateNeutral05: Color,
  val StateNeutral06: Color,
  val StatePositive01: Color,
  val StatePositive02: Color,
  val StatePositive03: Color,
  val StatePositive04: Color,
  val StatePositive05: Color,
  val StatePositive06: Color,
  val StateNegative01: Color,
  val StateNegative02: Color,
  val StateNegative03: Color,
  val StateNegative04: Color,
  val StateNegative05: Color,
  val StateNegative06: Color,
  val StateNotice01: Color,
  val StateNotice02: Color,
  val StateNotice03: Color,
  val StateNotice04: Color,
  val StateNotice05: Color,
  val StateNotice06: Color,
  val StateWarning01: Color,
  val StateWarning02: Color,
  val StateWarning03: Color,
  val StateWarning04: Color,
  val StateWarning05: Color,
  val StateWarning06: Color,
)
